version: '3'

services:
  trump-dev:
    build: .
    depends_on:
      - postgres
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"       
